### ISSUE TITLE
Live social wall

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wp20.wordpress.net#4]
Design:

| Desktop | Mobile |
|-|-|
| ![Live (Custom)](https://user-images.githubusercontent.com/1017872/225157126-1bb4790b-6186-472c-9e23-4830eb74b6db.png) | ![Live — Mobile](https://user-images.githubusercontent.com/1017872/225157139-885f1bef-dbaa-4dd3-8fe2-d339b0823880.png) |

TBC: Install https://smashballoon.com/social-wall/ plugin and configure social feeds

- [ ] remove Tagregator styles in `style.css`
- [ ] replace Tagregator shortcode in `page-live.php`

Update styling, consult @marko-srb

**Comment by StevenDufresne** [comment]
Update: waiting on the final plugin selection.

**Comment by marko-srb** [comment]
I asked Adam on Slack if the SmashBallon can be adjustable to the design in Figma. 

In case not, do let me know and I'll see to test it in order to see the limitations. Thanks!

**Comment by pablohoneyhoney** [comment]
Hey! Looking better than 15th, which I'm guessing we are reusing with similar constraints (which I don't fully know). 
Granted also I haven't read all the conversations before (so excuse if redundant), but here some things I see, not in special order:

- In wider screens, could we add more columns for more content? [This](https://wp15.wordpress.net/live/) is just expanding each card instead of adding more to see more at once. 
- In 15th, the modules aren't stacking well and empty spaces appear, something worth correcting for this anniversary (arguably for that one too if we find a way to do so). 
- Information density. Ideally we tight the top spacing so content peaks much higher. There are roughly 550px from top to first social card, which is on the edge for small screens. 
- Wayfinding. We should consider situating the user more clearly. Notice we don't say WordPress anywhere in the top area. I referred once to using the .org nav which would help (guessing isn't an option), but at least I'd consider adding the logo and /or name on the top left. The 20th is an image too, not text so we should consider a solution in terms of a11y.
- Verbally, I don't think we contextualize well what _Live_ means. It doesn't need to be long, but somewhat included in the text could help.  
- Line heights. We need to correct the line spacing within each social card. It's too lofty. 
- Navigation. Notice we don't have links to WP socials in this page, where they are more relevant. Neither clear access to WP itself. Perhaps adding them on footer could help?

<img width="1319" alt="Screen Shot 2023-03-15 at 6 38 42 PM" src="https://user-images.githubusercontent.com/25516611/225395987-4af7c68e-a1ee-435f-83ad-c7960e7e0d01.png">

None are hard blockers for starting implementation, things we can test in code, but they are issues to address before releasing. 

Side question: Are we feeding from other sources other than Twitter?

**Comment by jasmussen** [comment]
A quick visual stab at the above:

<img width="3480" alt="Frame 1000004419" src="https://user-images.githubusercontent.com/1204802/225575604-ea78ba14-a6f3-4bb2-ada2-59c7844594a7.png">

* A wider screen with 4 columns
* Tighter lineheights
* Moved the text prompt down below so the canvas of tweets is closer to the top
* Rephrased the "Live" to "#WP20 Live" as a replacement for the lowered prompt, and to contextualize more.

**Comment by pablohoneyhoney** [comment]
Some improvements! 

I think verbally we could be more explicit, explanatory, but design wise seems better. Perhaps even tighter in spacing within cards on the timestamp area. And could the masthead be less tall in cases/pages of content?

**Comment by jasmussen** [comment]
Nice. Here's a quick iteration on the compactness. 20px, 16px, 12px:

![I2, more compact cards](https://user-images.githubusercontent.com/1204802/225843038-5e0fe438-4c4e-485d-a696-ca9bd8512049.png)

As far as verbosity and header compactness, I tried moving the language selector and adding some text on the right. Also 2 sizes — I think we should be careful to scale the header down too much as it's such a key part of the visual language:

![compacter](https://user-images.githubusercontent.com/1204802/225845250-c4131975-5735-4e74-810f-c93b0d502045.png)

**Comment by marko-srb** [comment]
Hi everyone, 

Thank you so much for your time on this. It becomes a bit 'messy' but we'll bring it home soon. 

Here's the current status and overview per: 

**Video overview**

https://user-images.githubusercontent.com/111751264/225986512-01a4a4d6-6cd4-4094-95f4-3d993a1febf9.mp4

**Written overview**

Done: Most of the feedback is honored, except a one that is correlated to the 'embedding WordPress logo or text, or both in hero somewhere'; and development things

Next: New iteration on Monday and checking with Pablo on what's good. 

—

Thank you for your patience!

@jasmussen 
@pablohoneyhoney 
@adamwoodnz 
@StevenDufresne

**Comment by adamwoodnz** [comment]
Latest on plugin selection (as of March 18th)
> For now, we are sticking with Smash Balloon, but just using their Twitter feed… as the rest of their social wall plug-in doesn’t quite meet our needs/constraints. You can see it here: https://wp20.wordpress.net/twitter/. It looks great on mobile and decent on desktop. Not much design configuration options out of the box, but it can accommodate custom css of course.

**Comment by adamwoodnz** [comment]
> Next: New iteration on Monday and checking with Pablo on what's good.

The video was really helpful thanks @marko-srb. Any update this week?

**Comment by marko-srb** [comment]
@adamwoodnz 

Sorry for being silent. We are working on edits still and will ping you as soon as we have things done. I hope it can happen by Friday. 

On the other note: Are we able to customize the plugin (SmashBallon) as it looks in design? — can you tell this without actually making this page, hence it's not fully done?

Thank you!

**Comment by adamwoodnz** [comment]
> On the other note: Are we able to customize the plugin (SmashBallon) as it looks in design? — can you tell this without actually making this page, hence it's not fully done?

I can look into this today and report back 👍

**Comment by adamwoodnz** [comment]
> Are we able to customize the plugin (SmashBallon) as it looks in design?

@marko-srb I've added custom CSS to the live page at https://wp20.wordpress.net/twitter/ and got it very close. The main challenge looks to be adjusting the gap between cards to 20px. When I change the CSS the JS does not account for the extra space. Other things like moving the timestamp to the bottom can be achieved with a custom template, and that might be the solution for the spacing too. I'm pretty sure we can find a way which isn't too complicated.

So I think overall the answer is yes we can style it almost exactly as we want 🎉 

<img src="https://user-images.githubusercontent.com/1017872/227070786-55219beb-2963-4f95-9e51-64f768c0b45f.png" width="600" />

**Comment by adamwoodnz** [comment]
Closed by https://github.com/WordPress/wp20.wordpress.net/commit/e48ec663a71defea9f1686b2b7885f9043f48899
