### ISSUE TITLE
Reduce post except character length for `/news`

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wp20.wordpress.net#64]
The designs at full width don't have more than 2 lines. 

## Screenshot
<img width="739" alt="Screenshot 2023-04-12 at 2 40 24 PM" src="https://user-images.githubusercontent.com/1657336/231361512-dd1de361-55af-47dc-9730-ce8058043df1.png">

**Comment by iandunn** [comment]
🤔 I don't see any excerpts in the design that are cut off with a `...`, so I wonder if the intent was to have shorter excerpts that are manually added to the editor?

cc @marko-srb, @jasmussen, @DanSoschin

**Comment by jasmussen** [comment]
I don't mind the 3 line excerpts, especially for the manually entered ones. But happy to defer.

**Comment by marko-srb** [comment]
To help here with thinking behind this. 

@iandunn it is my mistake by not providing proper design with ... in the Figma. 

I noted this feedback in my previous video feedback. That issue was closed here on GH. 

—

I am ok with 3 lines as well, as long as we limit it to 3. At the moment, we have posts that have first paragraphs no longer than 3 rows. What happens if a paragraph that code pulls for News landing has 5 rows? I believe it will show 5 rows on landing. If that's the case, I'd keep this to 3 rows/lines as people seem to like it more than 2... 

Is that already the case, or behavior will pull the first paragraph, no matter its size/rows?

**Comment by iandunn** [comment]
Right now mobile/tablet breakpoints have `line-clamp: 2`, and desktop doesn't have any limit. We could set `line-clamp: 3` on the desktop (or all, if you also want 3 on mobile/tablet).

**Comment by marko-srb** [comment]
Let's leave = 2 on mobile/tablet, and on desktop/monitors = 3. Thank you! 🙏

**Comment by iandunn** [comment]
Sounds good 👍🏻
