### ISSUE TITLE
Sort events by date.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wp20.wordpress.net#79]
I don't understand the current sort, I imagine we should just sort by date?

**Comment by iandunn** [comment]
They are chronological in the raw data, and display that way on mobile:

https://github.com/WordPress/wp20.wordpress.net/blob/560a45fa7a24d1af9c95ef343e32cb0f78948857/wp-content/plugins/wp20-meetup-events/wp20-meetup-events.php#L252

![Screenshot 2023-04-14 at 7 40 22 AM](https://user-images.githubusercontent.com/484068/232075720-94bd3b2d-3515-4927-a41c-69f9674688e8.png)

On desktop we're using CSS `columns`, which causes them to sort left-to-right, rather than top to bottom.

![Screenshot 2023-04-14 at 7 42 53 AM](https://user-images.githubusercontent.com/484068/232076356-fbce0abe-2af1-40c9-a8ca-a0d377670b93.png)

I'm not sure if either method is more intuitive than the other, I can see it both ways. What do you think?

**Comment by StevenDufresne** [comment]
I guess I'm just confused by the last event:

<img width="1242" alt="Screenshot 2023-04-17 at 10 07 09 AM" src="https://user-images.githubusercontent.com/1657336/232355526-0c2da7a5-c395-4f87-9429-66d353e742dc.png">

I would expect may 9th to be in the first row.

**Comment by iandunn** [comment]
Oh, good catch! Something must be wrong there, I'll take a look.
